#!/usr/bin/env python3
"""Build `gen_vinhable`: King-vs-challenger DPO pairs from Albedo eval artifacts.

Both sides are Qwen3.6 candidates generated by production with `enable_thinking=True` and scored
by the same three-vote judge on the same checklist, so the label is the production score of each
rollout and the two sides think the same way. That removes the teacher/King asymmetry of
`sgp_vinhable`, where GLM references carry no reasoning at all.

Pair selection
    Every sample has two King and two challenger rollouts, so four King-vs-challenger pairings.
    A pairing is eligible when both rollouts have a score, at least four assistant turns, and the
    first behaviour group matches after both are cut into the same number (4-6) of groups. The
    winner must not carry the amputated-thinking flag (a rejected rollout may). Among eligible
    pairings the one with the largest score gap is kept; a sample whose best gap is zero is a tie.
    Runs are taken newest first, one pair per exact context, until the pair target is met; ties are
    kept at `--tie-share` of the released pairs.

Rows
    Progressive prefixes as in `sgp_vinhable`: sample k holds the first k behaviour groups of each
    side and only the final group's assistant turns carry `loss: true`. Harness-written turns
    (truncation notices) and empty turns are never supervised.

Thinking
    Assistant `content` is the exact text the model generated after the prompt's
    `<|im_start|>assistant\\n<think>\\n`: reasoning, `</think>`, then the action. About a quarter of
    production turns never close the think block. Re-rendering them through the chat template
    would insert an empty `<think>\\n\\n</think>` in front of them, which is the amputated-thinking
    fingerprint, so a trainer must render `<|im_start|>assistant\\n<think>\\n` + content +
    `<|im_end|>` verbatim. `think_closed` records whether the turn closed its think block.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Iterator

ROOT = Path(__file__).resolve().parents[1]
for location in (ROOT / "scripts", ROOT / "src"):
    if str(location) not in sys.path:
        sys.path.insert(0, str(location))

import build_sft_c_dataset as base  # noqa: E402
from albedo_eval_service.shared.observation_format import is_truncated  # noqa: E402
from build_joint_behavior_groups import validate_groups  # noqa: E402
from build_joint_behavior_groups_v2 import atomic_units, grouped  # noqa: E402
from build_new_batch_turn_pairs import identities, load_eval_keys, pool_split  # noqa: E402
from export_paired_king_c3q import canonical_messages, clean_messages  # noqa: E402

SCHEMA = "albedo-gen-dpo-v1"
SIDES = {
    "king": ("previous_king_turns", "king_error", "king_score", "king_amputated_thinking"),
    "challenger": ("challenger_turns", "chal_error", "challenger_score", "chal_amputated_thinking"),
}


def rows(path: Path, counts: Counter[str]) -> Iterator[dict[str, Any]]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                counts["skipped_truncated_artifact_line"] += 1


def compact(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def run_index(roots: list[Path]) -> list[dict[str, Any]]:
    """Every crawled run once, with dashboard metadata, newest first."""
    meta: dict[str, dict[str, Any]] = {}
    for root in roots:
        boards = list(root.glob("dashboard*.json")) + list(root.glob("dashboard-snapshots/*.json"))
        for path in boards:
            try:
                board = json.loads(path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue
            for run in board.get("eval_runs", []) if isinstance(board, dict) else []:
                if run.get("eval_run_id") and run.get("finished_at"):
                    meta[run["eval_run_id"]] = run
    runs: dict[str, dict[str, Any]] = {}
    for root in roots:
        for generated in (root / "runs").rglob("generated-samples.jsonl"):
            directory = generated.parent
            if directory.name in runs or not (directory / "scoring-results.jsonl").is_file():
                continue
            board = meta.get(directory.name, {})
            king = board.get("king") or {}
            runs[directory.name] = {
                "eval_run_id": directory.name,
                "directory": directory,
                "finished_at": board.get("finished_at") or "",
                "king_version": king.get("king_version"),
                "king_uid": king.get("uid"),
                "challenger_uid": board.get("uid"),
                "run_score_king": board.get("score_king"),
                "run_score_challenger": board.get("score_challenger"),
            }
    return sorted(runs.values(), key=lambda r: (r["finished_at"], r["eval_run_id"]), reverse=True)


def rollouts(run: dict[str, Any], counts: Counter[str]) -> Iterator[tuple[str, dict[str, Any], list[dict]]]:
    """(sample id, per-sample info, [rollout]) for every sample in a run."""
    directory = run["directory"]
    generated: dict[str, dict[int, dict[str, Any]]] = defaultdict(dict)
    for row in rows(directory / "generated-samples.jsonl", counts):
        base_id, _, replica = str(row["sample_id"]).partition("#r")
        generated[base_id][int(replica) if replica.isdigit() else 1] = row
    scoring: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows(directory / "scoring-results.jsonl", counts):
        scoring[str(row["sample_id"]).split("#", 1)[0]].append(row)
    for sid, scored in scoring.items():
        source = scored[0].get("question_source") or {}
        info = {
            "sample_phase": source.get("sample_phase"),
            "question_mode": source.get("question_mode"),
            "scoring_mode": scored[0].get("scoring_mode"),
        }
        found: list[dict[str, Any]] = []
        for replica, gen in sorted(generated.get(sid, {}).items()):
            if replica > len(scored):
                continue
            score_row = scored[replica - 1]
            for side, (turns_key, error_key, score_key, amputated_key) in SIDES.items():
                raw = gen.get(turns_key)
                score = score_row.get(score_key)
                if gen.get(error_key) or not isinstance(raw, list) or score is None:
                    counts[f"rollout_unusable:{side}"] += 1
                    continue
                try:
                    context, completion = base.split_turns(raw)
                except ValueError:
                    counts[f"rollout_unusable:{side}"] += 1
                    continue
                found.append({
                    "side": side,
                    "replica": replica,
                    "rollout_sample_id": str(gen["sample_id"]),
                    "context": clean_messages(context),
                    "completion": [
                        {"role": t["role"], "content": t["content"],
                         **({"harness_text": True} if t["role"] == "assistant" and is_truncated(t["content"]) else {})}
                        for t in raw[len(context):]
                        if isinstance(t, dict) and isinstance(t.get("content"), str)
                    ],
                    "score": float(score),
                    "amputated": bool(score_row.get(amputated_key)),
                })
        yield sid, info, found


def choose(prompt: list[dict], found: list[dict], counts: Counter[str]) -> dict[str, Any] | None:
    units = {}
    for rollout in found:
        units[id(rollout)] = atomic_units(rollout["completion"], prompt)
    best_gap, best, tie = -1.0, None, None
    kings = [r for r in found if r["side"] == "king"]
    challengers = [r for r in found if r["side"] == "challenger"]
    candidates = []
    for king in kings:
        for challenger in challengers:
            king_units, chal_units = units[id(king)], units[id(challenger)]
            turns = min(len(king_units), len(chal_units))
            if turns < 4:
                counts["pairing_rejected:fewer_than_four_turns"] += 1
                continue
            group_count = min(6, turns)
            king_groups = grouped(king_units, group_count)
            chal_groups = grouped(chal_units, group_count)
            if king_groups[0]["dominant_behavior"] != chal_groups[0]["dominant_behavior"]:
                counts["pairing_rejected:first_group_mismatch"] += 1
                continue
            gap = round(king["score"] - challenger["score"], 6)
            winner = king if gap > 0 else challenger if gap < 0 else None
            if winner is not None and winner["amputated"]:
                counts["pairing_rejected:winner_amputated_thinking"] += 1
                continue
            candidates.append((abs(gap), king["replica"], challenger["replica"]))
            entry = {
                "gap": gap, "group_count": group_count,
                "king": king, "challenger": challenger,
                "king_groups": king_groups, "challenger_groups": chal_groups,
            }
            if gap == 0:
                tie = tie or entry
            elif abs(gap) > best_gap:
                best_gap, best = abs(gap), entry
    chosen = best or tie
    if chosen is not None:
        chosen["candidates"] = sorted(candidates, reverse=True)
        for side in ("king", "challenger"):
            validate_groups(chosen[side]["completion"], chosen[f"{side}_groups"], chosen["group_count"])
    return chosen


def flatten(groups: list[dict], upto: int) -> list[dict]:
    messages: list[dict] = []
    for index, group in enumerate(groups[:upto], 1):
        target = index == upto
        for message in group["messages"]:
            item = {"role": message["role"], "content": message["content"]}
            if message["role"] == "assistant":
                item["think_closed"] = "</think>" in message["content"]
                if message.get("harness_text"):
                    item["harness_text"] = True
                supervised = target and bool(message["content"].strip()) and not message.get("harness_text")
            else:
                supervised = False
            item["loss"] = supervised
            messages.append(item)
    return messages


def emit(pair: dict[str, Any], counts: Counter[str]) -> Iterator[dict[str, Any]]:
    entry = pair["entry"]
    winner = "king" if entry["gap"] > 0 else "challenger"
    loser = "challenger" if winner == "king" else "king"
    if entry["gap"] == 0:
        winner, loser = "king", "challenger"  # arbitrary for a tie; `preference` says tie
    chosen_groups, rejected_groups = entry[f"{winner}_groups"], entry[f"{loser}_groups"]
    total = entry["group_count"]
    aligned = sum(
        a["dominant_behavior"] == b["dominant_behavior"] for a, b in zip(chosen_groups, rejected_groups)
    )
    prompt = [{"role": m["role"], "content": m["content"], "loss": False} for m in pair["prompt"]]
    for k in range(1, total + 1):
        chosen, rejected = flatten(chosen_groups, k), flatten(rejected_groups, k)
        if not any(m["loss"] for m in chosen) or not any(m["loss"] for m in rejected):
            counts["samples:dropped_no_supervised_turn"] += 1
            continue
        yield {
            "schema": SCHEMA,
            "pair_id": pair["pair_id"],
            "sample_uid": f"{pair['pair_id']}#k{k}",
            "prefix_groups": k,
            "group_count": total,
            "is_full_trajectory": k == total,
            "split": pair["split"],
            "sample_id": pair["sample_id"],
            "task_group": pair["task_group"],
            "source": pair["sample_id"].split("/", 1)[0],
            "sample_phase": pair["info"]["sample_phase"],
            "question_mode": pair["info"]["question_mode"],
            "scoring_mode": pair["info"]["scoring_mode"],
            "eval_run_id": pair["run"]["eval_run_id"],
            "finished_at": pair["run"]["finished_at"],
            "king_version": pair["run"]["king_version"],
            "challenger_uid": pair["run"]["challenger_uid"],
            "prompt": prompt,
            "chosen": chosen,
            "rejected": rejected,
            "preference": "tie" if entry["gap"] == 0 else winner,
            "chosen_side": winner,
            "rejected_side": loser,
            "chosen_rollout": entry[winner]["rollout_sample_id"],
            "rejected_rollout": entry[loser]["rollout_sample_id"],
            "king_score": entry["king"]["score"],
            "challenger_score": entry["challenger"]["score"],
            "margin": abs(entry["gap"]),
            "rejected_amputated_thinking": entry[loser]["amputated"],
            "eligible_pairings": len(entry["candidates"]),
            "aligned_groups": aligned,
            "aligned_fraction": round(aligned / total, 6),
            "chosen_behavior_sequence": [g["dominant_behavior"] for g in chosen_groups[:k]],
            "rejected_behavior_sequence": [g["dominant_behavior"] for g in rejected_groups[:k]],
            "prompt_sha256": hashlib.sha256(compact(pair["prompt"]).encode()).hexdigest(),
        }


def build(args: argparse.Namespace) -> None:
    args.out.mkdir(parents=True, exist_ok=False)
    counts: Counter[str] = Counter()
    eval_keys = load_eval_keys(args.eval_batch)
    target_non_tie = int(round(args.pairs * (1 - args.tie_share)))
    spool_path = args.out / ".pairs.jsonl"
    seen_contexts: set[str] = set()
    non_tie, ties = [], []
    runs_used = 0
    with spool_path.open("w", encoding="utf-8", newline="\n") as spool:
        for run in run_index(args.crawl):
            if len(non_tie) >= target_non_tie:
                break
            runs_used += 1
            for sid, info, found in rollouts(run, counts):
                counts["samples_seen"] += 1
                if not found:
                    counts["sample_dropped:no_usable_rollout"] += 1
                    continue
                contexts = {base.sha(canonical_messages(r["context"])) for r in found}
                if len(contexts) != 1:
                    counts["sample_dropped:rollout_contexts_differ"] += 1
                    continue
                prompt = found[0]["context"]
                keys = identities(sid, prompt)
                if keys[2] in seen_contexts:
                    counts["sample_dropped:context_seen_in_newer_run"] += 1
                    continue
                if eval_keys.intersection(keys[:2]):
                    counts["sample_dropped:task_in_eval_batch"] += 1
                    continue
                entry = choose(prompt, found, counts)
                if entry is None:
                    counts["sample_dropped:no_eligible_pairing"] += 1
                    continue
                seen_contexts.add(keys[2])
                pair = {
                    "pair_id": hashlib.sha256(
                        f"{run['eval_run_id']}\0{sid}\0{entry['king']['replica']}\0"
                        f"{entry['challenger']['replica']}".encode()).hexdigest(),
                    "sample_id": sid, "task_group": keys[0], "split": pool_split(keys[0]),
                    "run": {k: v for k, v in run.items() if k != "directory"},
                    "info": info, "prompt": prompt, "entry": entry,
                }
                (ties if entry["gap"] == 0 else non_tie).append(len(non_tie) + len(ties))
                slim = {k: v for k, v in entry.items() if k not in ("king", "challenger")}
                for side in ("king", "challenger"):
                    slim[side] = {k: entry[side][k] for k in
                                  ("replica", "rollout_sample_id", "score", "amputated")}
                spool.write(compact({**pair, "entry": slim}) + "\n")
                if len(non_tie) >= target_non_tie:
                    break
            print(f"{run['finished_at'][:16]} {run['eval_run_id'][:8]} runs={runs_used} "
                  f"pairs={len(non_tie)} ties={len(ties)}", flush=True)

    tie_budget = int(round(len(non_tie) * args.tie_share / (1 - args.tie_share)))
    random.seed(args.seed)
    kept_ties = set(random.sample(ties, min(tie_budget, len(ties))))
    released = set(non_tie) | kept_ties

    handles = {s: (args.out / f"{s}.jsonl").open("w", encoding="utf-8", newline="\n") for s in ("train", "dev")}
    oldest = newest = None
    try:
        with spool_path.open(encoding="utf-8") as spool:
            for index, line in enumerate(spool):
                if index not in released:
                    continue
                pair = json.loads(line)
                split = pair["split"]
                preference = "tie" if pair["entry"]["gap"] == 0 else (
                    "king" if pair["entry"]["gap"] > 0 else "challenger")
                counts[f"pairs:{split}"] += 1
                counts[f"pairs:preference:{preference}"] += 1
                counts[f"pairs:king_version:{pair['run']['king_version']}"] += 1
                counts[f"pairs:question_mode:{pair['info']['question_mode']}"] += 1
                finished = pair["run"]["finished_at"]
                oldest = min(oldest or finished, finished)
                newest = max(newest or finished, finished)
                for sample in emit(pair, counts):
                    handles[split].write(compact(sample) + "\n")
                    counts[f"samples:{split}"] += 1
                    counts[f"samples:k{sample['prefix_groups']}"] += 1
    finally:
        for handle in handles.values():
            handle.close()
        spool_path.unlink(missing_ok=True)

    pairs = counts["pairs:train"] + counts["pairs:dev"]
    summary = {
        "schema": "albedo-gen-dpo-summary-v1",
        "counts": dict(sorted(counts.items())),
        "pairs": pairs,
        "samples": counts["samples:train"] + counts["samples:dev"],
        "tie_share_of_pairs": round(counts["pairs:preference:tie"] / pairs, 4) if pairs else None,
        "runs_used": runs_used,
        "finished_at_range": [oldest, newest],
        "selection": {
            "run_order": "newest first; one pair per exact context (the newest run wins)",
            "pairing": "best score gap among the 4 King x challenger rollout pairings that pass "
                       "the filters; one side is always King, the other challenger",
            "filters": ["both rollouts scored", ">= 4 assistant turns per side",
                        "4-6 equal behaviour groups", "first behaviour group matches",
                        "winner not flagged amputated_thinking", "task not in local eval batch"],
            "tie_share": args.tie_share,
            "label": "production three-vote score of each rollout on the run's checklist",
        },
        "loss_contract": {
            "assistant_tokens_of_the_final_group_only": True,
            "earlier_groups_are_unsupervised_context": True,
            "observations_are_context": True,
            "harness_text_and_empty_turns": "loss false",
        },
        "think_contract": {
            "content": "exact generation after '<|im_start|>assistant\\n<think>\\n'",
            "render": "'<|im_start|>assistant\\n<think>\\n' + content + '<|im_end|>' verbatim; "
                      "never through the chat template",
            "think_closed": "false for turns that never closed the think block",
        },
    }
    (args.out / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    storage = Path("E:/albedo-storage-temp")
    parser.add_argument("--crawl", type=Path, action="append", default=[
        storage / "raw-rollouts-current-20260923",
        storage / "raw-rollouts-current-20260916",
        storage / "raw-rollouts-current-20260908",
    ])
    parser.add_argument("--eval-batch", type=Path, action="append",
                        default=[ROOT / "reports/cxxv-full-eval-400-20260913/batch-400.jsonl"])
    parser.add_argument("--pairs", type=int, default=12250)
    parser.add_argument("--tie-share", type=float, default=0.02)
    parser.add_argument("--seed", type=int, default=97)
    parser.add_argument("--out", type=Path, required=True)
    build(parser.parse_args())


if __name__ == "__main__":
    main()
